project:
  type: website

website:
  title: "Clases UAI"
  repo-url: https://github.com/datacubeR/clases_UAI
  repo-actions: [issue]
  page-navigation: true
  back-to-top-navigation: true
  page-footer: 
    left: "Copyright 2024, [Alfonso Tobar-Arancibia](https://datacuber.cl)" 
  navbar:
    logo: logo.jpg
    background: "#000000"
    search: true
    right:
      - href: index.qmd
        text: Acerca de Mí
      - sidebar:slides
  sidebar: 
    - id: slides
      title: Cursos
      contents: 
        - text: TICS 411 - Minería de Datos
          href: tics411.qmd

format:
  html:
    theme: default
    css: styles.css