project:
  type: website

website:
  title: "Clases UAI"
  repo-url: https://github.com/datacubeR/clases_UAI
  repo-actions: [issue]
  page-navigation: true
  back-to-top-navigation: true
  page-footer: 
    left: "Copyright 2024, [Alfonso Tobar-Arancibia](https://datacuber.cl)" 
  navbar:
    logo: logo.jpg
    background: "#000000"
    search: true
    right:
      - href: index.qmd
        text: Acerca de Mí
      - href: charlas.qmd
        text: Charlas
      - sidebar:tics411
  sidebar: 
    - id: tics411
      title: Tics411-Minería de Datos
      contents: 
        - text: Diapositivas del Curso
          href: tics411.qmd
        - text: Notebooks
          href: tics411-labs.qmd
format:
  html:
    theme: default
    css: styles.css